name: QuantumsHerobrine
version: '${version}'
main: io.github.greasyrooster1.quantumsherobrine.QuantumsHerobrine
api-version: '1.20'
commands:
  test:
    description: [QH] just a test
    usage: /test
  heal:
    description: [QH] heals a player
    usage: /heal [player]
    aliases: hp
