name: QuantumsHerobrine
version: '${version}'
main: io.github.greasyrooster1.quantumsherobrine.QuantumsHerobrine
api-version: '1.20'
depend: [Citizens]
commands:
  test:
    description: just a test
    usage: /test
  heal:
    description: heals yourself
    usage: /heal
